// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://fsyescuzqhuysgevtqhp.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6ImZzeWVzY3V6cWh1eXNnZXZ0cWhwIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NDkxMDU2NzEsImV4cCI6MjA2NDY4MTY3MX0.xYqlQ90NfhLjXkrgCYuKBB0yv2oe7rqgppvU5cm83-w";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY);